### ISSUE TITLE
Erreur lors de l'authentification : Erreur interne !

### ISSUE THREAD

**Issue by Nicolas-Hermet** [dguehennec/ZimbraMailNotifier#2]
Hi,

First I deeply apologize for the french Title. But I thought that the original error message would be more accurate to read.

I'm a convicted user of ZimbraMailNotifier. It has been working soo smootlhy for years now.
But since a few weeks now (I couldn't say when exactly), an error occur during the authentication.
Though : nothing changed on my configuration except maybe the chrome version : 

- windows 10
- Chrome : 72.0.3626.119 (Build officiel) (64 bits)
- 2 differents free accounts on https://zimbra.free.fr/

I still can connect myself manually on zimbra.free.fr/ if I deactivate the extension and it works fine.

What can possibly go wrong ?

Here are the error message and behaviour : 
![image](https://user-images.githubusercontent.com/38986312/53240203-5f1d5000-369e-11e9-9f74-9e7ab6248474.png)

![image](https://user-images.githubusercontent.com/38986312/53240240-75c3a700-369e-11e9-8b63-59850a349368.png)
In this last screen shot, I just click on the connect button and took the snapshot during the message 

> "Pour avoir des notifications, veuillez-vous connecter." 

But after a short time (~0.3 - 0.5 seconds) the message 

> "Erreur lors de l'authentification : authentification expirée !" pops up again.

Any idea what's going on ? 
How can I help ?

Thank you forward anyway

**Comment by dguehennec** [comment]
I have the same issue with my Free account too, I will search the cause of the problem this weekend

No problem with Firefox

**Comment by Nicolas-Hermet** [comment]
Great !

Let me know if I can be of any help

**Comment by dguehennec** [comment]
the problem is that I can not recover cookies for Free connection.
May be linked to a chrome update

**Comment by dguehennec** [comment]
Fixed in version 2.7.4

**Comment by Nicolas-Hermet** [comment]
Thanks a lot !

**Comment by Nicolas-Hermet** [comment]
Hi @dguehennec ,

Sorry to come again here, but the issue is not fixed for me. 
I'm in version 2.7.4 with chrome 72.0.3626.121 (official build / 64bits).
I did uninstall and install again the extension, but the same problem occur.

Is there something special to do to make this right ?

Let me know I can be of any help.

**Comment by dguehennec** [comment]
Hi,

I think there is a difference between chrome under ubuntu and under windows

the problem is related to a modification of the function specification in version 72, it seems to work differently from one to another

I will check that...

**Comment by Nicolas-Hermet** [comment]
Hi !
Thank you very much for that !

**Comment by Owned67** [comment]
Hello same error with Opera only, work for chrome (Windows 10)
![Noname](https://user-images.githubusercontent.com/1497809/82480089-93670280-9ad3-11ea-868f-21004907cbd6.jpg)

**Comment by Nicolas-Hermet** [comment]
@Owned67 @dguehennec  : ok I just found now what was my issue. In the hope it can be helpfull to others too.

![image](https://user-images.githubusercontent.com/38986312/86259872-dcbf6d00-bbbc-11ea-8217-2749590d3e7e.png)

Option was on `when I clic on the extension` hence the extension broke. 

You have to authorize the extension to every web site for it to work properly.

Good to know.

**Comment by Owned67** [comment]
C'est déjà configuré comme dans ton screen sur Opera et l'erreur persiste
